###
GET http://localhost:8080/rest/user/all

###
GET http://localhost:8080/rest/simulation/all

###
GET http://localhost:8080/rest/simulation/2

###
POST http://localhost:8080/rest/simulation/run8
Content-Type: application/json

{
  "lastInput": "2022-11-22",
  "user": {
    "userId": 3,
    "email": "colin@gmail.com"
  },
  "ageAircraft": 25,
  "noOfPassengers": 1,
  "picLicence": "student",
  "picAge": 67,
  "totalHrs": 34,
  "typeHrs": 1,
  "ninetyDayHrs": 1,
  "twentyEightDayHrs": 1,
  "dayOfWeek": null
}

###
POST http://localhost:8080/rest/simulation/run9
Content-Type: application/json

{
  "lastInput": "2022-11-22",
  "user": {
    "userId": 1,
    "email": "adam@gmail.com"
  },
  "ageAircraft": 50,
  "noOfPassengers": 1,
  "picLicence": "airline transport pilot licence",
  "picAge": 52,
  "totalHrs": 10000,
  "typeHrs": 1,
  "ninetyDayHrs": 1,
  "twentyEightDayHrs": 1,
  "dayOfWeek": "Wed"
}

###
POST http://localhost:8080/rest/simulation/update/2
Content-Type: application/json

{
  "lastInput": "2023-04-17",
  "user": {
    "userId": 2,
    "email": "bob@gmail.com"
  },
  "ageAircraft": 22,
  "noOfPassengers": 2,
  "picLicence": "student",
  "picAge": 22,
  "totalHrs": 22,
  "typeHrs": 22,
  "ninetyDayHrs": 22,
  "twentyEightDayHrs": 22,
  "dayOfWeek": "Sat"
}

###
POST http://localhost:8080/rest/simulation/update/1
Content-Type: application/json

{
  "lastInput": "2023-04-17",
  "user": {
    "userId": 1,
    "email": "adam@gmail.com"
  },
  "ageAircraft": 11,
  "noOfPassengers": 1,
  "picLicence": "private pilot licence",
  "picAge": 31,
  "totalHrs": 1111,
  "typeHrs": 11,
  "ninetyDayHrs": 111,
  "twentyEightDayHrs": 11,
  "dayOfWeek": null
}

###
DELETE http://localhost:8080/rest/simulation/delete/3

###
POST http://localhost:8080/rest/user/add
Content-Type: application/json

{
  "email": "dave@gmail.com",
  "password": "password4"
}

###
POST http://localhost:8080/rest/user/login
Content-Type: application/json

{
  "email": "dave@gmail.com",
  "password": "password4"
}

